// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_AND']!,
    appId: dotenv.env['APP_ID_AND']!,
    messagingSenderId: '1054039258694',
    projectId: 'checkpoint6-e87bd',
    storageBucket: 'checkpoint6-e87bd.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_IOS']!,
    appId: dotenv.env['APP_ID_IOS']!,
    messagingSenderId: '1054039258694',
    projectId: 'checkpoint6-e87bd',
    storageBucket: 'checkpoint6-e87bd.firebasestorage.app',
    iosBundleId: 'br.com.guiengel.geradorDeSenha',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_WIN']!,
    appId: dotenv.env['APP_ID_WIN']!,
    messagingSenderId: '1054039258694',
    projectId: 'checkpoint6-e87bd',
    authDomain: 'checkpoint6-e87bd.firebaseapp.com',
    storageBucket: 'checkpoint6-e87bd.firebasestorage.app',
  );
}
